services:
  mysql:
    image: mariadb:10.3.39
    env_file:
      - .env

    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always

  fastapi:
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app 
    depends_on:
      - mysql
    command: uvicorn main:app --host 0.0.0.0 --port 3010 --reload
    restart: always

# volumes:
#   mysql-data:
