services:
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    env_file:
      - .env
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mariadb", "-h", "${MARIADB_HOST}", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  fastapi:
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app 
    depends_on:
      mysql:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 3010 --reload
    restart: always
